# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Yellow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yellow
  pod 'HyphenateChat_Circle'
  pod 'Alamofire'
  pod 'MessageKit'
  pod 'LTMorphingLabel'
  pod 'SPIndicator'
  pod 'LeanCloud/Foundation'
#  pod 'Kingfisher'
  pod 'TagListView'
  pod 'SwiftEntryKit'
  pod 'SPAlert'
  pod 'BadgeSwift'
  pod 'BadgeHub'
  pod 'EmptyDataSet-Swift'
  
end
